name: firm-mmtta
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu124
      - torch==2.5.1
      - torchvision==0.20.1
      - torchaudio==2.5.1
      - -r requirements.txt
